#! /bin/sh 
# PHRI ROS Startup Script
/opt/ros/fuerte/setup.sh
export ROS_OS_OVERRIDE=debian:squeeze
export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:/home/pi/Desktop/rostest/:/home/pi/ros-pkg:/home/pi/phri_ros
sudo /usr/bin/amixer set PCM -- 70%

/opt/ros/fuerte/bin/roslaunch phri_ros full.launch