#! /bin/sh 
gpio export 17 out
gpio export 18 out
gpio export 21 out
gpio export 22 out
gpio export 23 out
gpio export 24 out

gpio export 14 in
gpio -g mode 14 up

gpio export 15 in
gpio -g mode 15 up


